### ISSUE TITLE
In some cases `opam build` fails with `internal error, uncaught exception: Not_found`

### ISSUE THREAD

**Issue by gridbugs** [kit-ty-kate/opam-build#6] opened 2023-08-01 02:04 UTC
I tried running `opam build` in a simple ocaml project with a single package defined and I got this error. I'm not sure what is exceptional about this package, but to reproduce the problem, run:
```
git clone https://github.com/gridbugs/vendredi
cd vendredi
opam build
...
∗ installed ppxlib.0.30.0
∗ installed ppx_sexp_conv.v0.16.0
Done.
# Run eval $(opam env) to update the current shell environment
opam-build: internal error, uncaught exception:
            Not_found
```

It does seem to correctly set up the switch despite the error.

My OS is NixOS and my opam is version 2.1.5.

**Comment by kit-ty-kate** [comment] 2024-02-24 21:07
Duplicate of #4.
I just tested to make sure and it was fixed by the same commit. Thanks for your bug-report!

**Closed as completed by kit-ty-kate** 2024-02-24 21:07 UTC
